name: Deploy
on:
  # Triggers this Action on push or pull request events on the "main" branch and when manually requested from the "Actions" tab
  push:
    branches: [ cdpipeline_implementatoin ]
  workflow_dispatch:

jobs:
  deploy_code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Ansible playbook
        uses: dawidd6/action-ansible-playbook@v2.5.0
        with:
          playbook: deploy-playbook.yml # path to your Ansible playbook
          directory: .github/workflow/
          key: ${{ secrets.ansible_key }} # the ssh private key for ansible to use to connect to the servers, stored as "ansible_ssh_private_key" in the GitHub secrets
          inventory: ${{ secrets.ansible_playbook }} # the ansible inventory to use, stored as "ansible_inventory" in the GitHub secrets