name: Java CI with Maven

on:
  push:
    branches: [ updatedCustomerAccount ]
  pull_request:
    branches: [ updatedCustomerAccount ]


jobs:
  build:
    runs-on: ubuntu-latest # is Ubuntu environment

    # ... some other config ...

    steps:
      # ... some prepare steps, like action/checkout, run some script without MySQL, etc.

      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up JDK 1.11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Shutdown Ubuntu MySQL (SUDO)
        run: sudo service mysql stop # Shutdown the Default MySQL, "sudo" is necessary, please not remove it

      # ... Set-up MySQL configuration, see Usage
      #- name: Set up MySQL
      #- uses: mirromutth/mysql-action@v1.1
      #  with:
      #    mysql database: 'roadSideAssistance' # Optional, default value is "test". The specified database which will be create
      #    mysql root password: root # Required if "mysql user" is empty, default is empty. The root superuser password
      #    mysql user: 'user' # Required if "mysql root password" is empty, default is empty. The superuser for the specified database. Can use secrets, too
      #    mysql password: password # Required if "mysql user" exists. The password for the "mysql user"
      #   # ... some steps after set-up MySQL ...

      - name: Build
        run: mvn --batch-mode -DskipTests package

      - name: Test
        run: mvn --batch-mode -Dmaven.test.failure.ignore=true test

      #- name: Report
      #  uses: dorny/test-reporter@v1
      #  if: always()
      #  with:
      #    name: Maven Tests
      #    path: target/surefire-reports/*.xml
      #    reporter: java-junit
      #    fail-on-error: true
    # ... some another config ...