name: 'React Test Report'
on:
  workflow_run:
    workflows: ['React CI']                     # runs after CI workflow
    types:
      - completed
defaults:
  run:
    working-directory: FrontEnd
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
    - uses: dorny/test-reporter@v1
      with:
        artifact: react-test-results            # artifact name
        name: JEST Tests                  # Name of the check run which will be created
        path: '*.xml'                     # Path to test results (inside artifact .zip)
        reporter: jest-junit              # Format of test results